### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by tbe** [1and1/pg-exporter#1]
Currently, there are no tests, suitable for CI.

The only component that could be tested "stateless" is the code generator.
Most of the code requires running PostgreSQL instances in different versions during testing.

I'm open for any ideas and help.

**Comment by df7cb** [comment]
What do you think about the idea in https://github.com/credativ/pg-exporter/tree/testsuite ?

It's running the exporter against some PG version, normalizes most of the numbers in the output, and diffs the result against a static file.

**Comment by tbe** [comment]
This will ensure that the exporter runs with a specific version. And may be a good start. But:
 
If a metric is not populated, because of a bug in the model or queries, the resulting metric will be 0.

I thought of dumping `pg_catalog` in an own schema and override the search path for the test-runs of the exporter.

That would require an upgrade to https://github.com/uptrace/bun, the successor of go-pg, as the URL parser can handle search_path. (Also, it would drop the requirement for my ugly self-build parser)
